name: Build OPPO R11/R11s/R15x/K1 Kernel and AnyKernel3
on:

  workflow_dispatch:

jobs:
  OPPO-R11:
    uses: ./.github/workflows/Kbuild_16051.yml
  OPPO-R11s:
    uses: ./.github/workflows/Kbuild_17011.yml
  OPPO-R15x/K1:
    uses: ./.github/workflows/Kbuild_18005.yml