name: Build OPPO R11/R11s/R15x/K1 Kernel and AnyKernel3
on:

  workflow_dispatch:

jobs:
  build:
    Build OPPO R11 Kernel:
      uses: ./.github/workflows/Kbuild_16051.yml
    Build OPPO R11s Kernel:
      uses: ./.github/workflows/Kbuild_17011.yml
    Build OPPO R15x/K1 Kernel:
      uses: ./.github/workflows/Kbuild_18005.yml